In [ ]:
#importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving KDDTrain+.csv to KDDTrain+.csv


In [ ]:
import io
dataset = pd.read_csv(io.BytesIO(uploaded['KDDTrain+.csv']))
dataset.head(10)

duration protocol_type  ... dst_host_srv_rerror_rate    class
0         0           tcp  ...                     0.00   normal
1         0           udp  ...                     0.00   normal
2         0           tcp  ...                     0.00  anomaly
3         0           tcp  ...                     0.01   normal
4         0           tcp  ...                     0.00   normal
5         0           tcp  ...                     1.00  anomaly
6         0           tcp  ...                     0.00  anomaly
7         0           tcp  ...                     0.00  anomaly
8         0           tcp  ...                     0.00  anomaly
9         0           tcp  ...                     0.00  anomaly

[10 rows x 42 columns]

In [ ]:
dataset.isnull().values.any()

False

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

featured_columns = dataset[['protocol_type', 'service', 'flag', 'count', 'srv_count']]

featured_columns['protocol_type'] = label_encoder.fit_transform(featured_columns['protocol_type'])
featured_columns['service'] = label_encoder.fit_transform(featured_columns['service'])
featured_columns['flag'] = label_encoder.fit_transform(featured_columns['flag'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pan

In [ ]:
predicted_class = dataset[['class']]
predicted_class['class'] = label_encoder.fit_transform(predicted_class['class'])

predicted_class.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


class
0      1
1      1
2      0
3      1
4      1

In [ ]:
x = featured_columns[['protocol_type', 'service', 'flag', 'count', 'srv_count']]
y = predicted_class['class']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.9, random_state = 5)

print(x)
print(y)

        protocol_type  service  flag  count  srv_count
0                   1       20     9      2          2
1                   2       44     9     13          1
2                   1       49     5    123          6
3                   1       24     9      5          5
4                   1       24     9     30         32
...               ...      ...   ...    ...        ...
125968              1       49     5    184         25
125969              2       49     9      2          2
125970              1       54     9      1          1
125971              1       30     5    144          8
125972              1       20     9      1          1

[125973 rows x 5 columns]
0         1
1         1
2         0
3         1
4         1
         ..
125968    0
125969    1
125970    1
125971    0
125972    1
Name: class, Length: 125973, dtype: int64


In [ ]:
# Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier

random_forest_model = RandomForestClassifier()
random_forest_model.fit(x_train, y_train.ravel())
y_pred = random_forest_model.predict(x_test)


print("Accuracy - Random Forest Classifier:\n{0:.3f}".format(metrics.accuracy_score(y_test, y_pred)))

cm_rfc = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n",cm_rfc)

print(classification_report(y_test, y_pred))

Accuracy - Random Forest Classifier:
0.976
Confusion Matrix:
 [[50386  2371]
 [  400 60219]]
              precision    recall  f1-score   support

           0       0.99      0.96      0.97     52757
           1       0.96      0.99      0.98     60619

    accuracy                           0.98    113376
   macro avg       0.98      0.97      0.98    113376
weighted avg       0.98      0.98      0.98    113376



In [ ]:
# Naive Bayes Classifier

from sklearn.naive_bayes import GaussianNB

naive_bayes_model = GaussianNB()
naive_bayes_model.fit(x_train, y_train.ravel())
y_pred = naive_bayes_model.predict(x_test)
print("Accuracy - Naive Bayes Classifier:\n{0:.3f}".format(metrics.accuracy_score(y_test, y_pred)))
cm_nbc = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n",cm_nbc)
print(classification_report(y_test, y_pred))

Accuracy - Naive Bayes Classifier:
0.858
Confusion Matrix:
 [[42482 10275]
 [ 5851 54768]]
              precision    recall  f1-score   support

           0       0.88      0.81      0.84     52757
           1       0.84      0.90      0.87     60619

    accuracy                           0.86    113376
   macro avg       0.86      0.85      0.86    113376
weighted avg       0.86      0.86      0.86    113376



In [ ]:
#Decision Tree Classifier

from sklearn.tree import DecisionTreeClassifier

decision_tree_model = DecisionTreeClassifier()
decision_tree_model.fit(x_train, y_train.ravel())
y_pred = decision_tree_model.predict(x_test)
print("Accuracy - Decision Tree Classifier:\n{0:.3f}".format(metrics.accuracy_score(y_test, y_pred)))
cm_dtc = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n",cm_dtc)
print(classification_report(y_test, y_pred))

Accuracy - Decision Tree Classifier:
0.974
Confusion Matrix:
 [[50263  2494]
 [  428 60191]]
              precision    recall  f1-score   support

           0       0.99      0.95      0.97     52757
           1       0.96      0.99      0.98     60619

    accuracy                           0.97    113376
   macro avg       0.98      0.97      0.97    113376
weighted avg       0.97      0.97      0.97    113376

